feat(apps/gql): change mutation payload types (#608)
This is changing the payload types to be more predictable:

before:
```graphql
union CreatePanoPostPayload = PanoPost | NotAuthorized | InvalidInput
```
after:
```graphql
type CreatePanoPostPayload {
  edge: PanoPostEdge
  error: CreatePanoPostError
}

union CreatePanoPostError = NotAuthorized | InvalidInput
```

The reason is that relay wants us to return an edge typed object to be
able to update related connections (eg. When a post is added, update the
pano feed on pano home page)

https://relay.dev/docs/next/guided-tour/list-data/updating-connections